### PR TITLE
Proposing an alternative flow rate model

### PR DESCRIPTION
**Pull request by illuzn**
I think a directly proportional model makes far more sense i.e. if current doubles then twice as many dots flow.

### CODE REVIEW

**Comment by ulic75** [comment]
For the most part I like it.  The only issue I have is that the flow lines, in and out of solar and battery exist partially behind the entity circles and sometimes the dots flow sooo slowly it appears as if there isn't a dot for a significant amount of time.

So until the svg paths can be redesigned while still maintaining some responsiveness I think this flow proposal will have to be on hold.

**Comment by ulic75** [comment]
For the most part I like it.  The only issue I have is that the flow lines, in and out of solar and battery exist partially behind the entity circles and sometimes the dots flow sooo slowly it appears as if there isn't a dot for a significant amount of time.

So until the svg paths can be redesigned while still maintaining some responsiveness I think this flow proposal will have to be on hold.

**Comment by TheFelix93** [comment]
Can't you just add an offset to the minimum value, that ensures a minimal speed which is visible? I exchange subtract that offset from the maximum value to be symetrical again, based on the given entries.

Just as an idea, not sure if it fully works.

**Comment by rfspereira** [comment]
The formula uses a min and max value.... 
Suggestion:
Add two optional properties to the component, one for min and one for max.
If these properties are "populated" by who's using the card, their values are used to calculate the flow rate with the following rules:
a) if value Below or equal to minimum the dots go slow
b) if value  between min and max, use the same math as today
c) if value equal or above max, then fast speed.

If the user does not specify a min or max (notice it must specify both for above rule to be usable) then it words as it is today...

**Comment by abreingan** [comment]
Hi this is a bit left field, but to make the dots representative the actual current (ahhm) values for each flow is needed. so Grid +-, Load +- and Solar + (as of the last state value).

This would have the benefit of being able to show the instantaneous values (eg not only solar production today (Kwh) but solar production now in Kw.

**Pull request closed without merging**
