### PR TITLE
feat: Open Entity details on click

### PR DESCRIPTION
**Pull request by Patrick762**
This PR opens the typical Home Assistant Entity Details Popup if any of the circles is clicked (except the Home circle)

### CODE REVIEW

**Comment by Patrick762** [comment]
If someone wants to test, here's the js file:

[power-flow-card.zip](https://github.com/ulic75/power-flow-card/files/10393438/power-flow-card.zip)

**Comment by Rhysgh** [comment]
Stupid question time.. how can i access this code in HA?

**Comment by mb-software** [comment]
I have tested this by copying and replacing the .js file inside the www/community folder. Not sure what to do with the .js.gz file, so I just deleted this?!
It works very well. Just a small issue: the mouse pointer does not change on hover so it does not appear as clickable.

And for me unfortunately it does not work in the HA app on Android. But maybe that is an issue with the cache?

**Comment by Rhysgh** [comment]
i must be super thick i cant work out where the code is to copy .. in git hub.

**Comment by Patrick762** [comment]
New version with pointer @mb-software :

[power-flow-card.zip](https://github.com/ulic75/power-flow-card/files/10415420/power-flow-card.zip)

I had to try another filename for every new version (to prevent caching). Maybe that's the problem on your Android app @mb-software

**Comment by mb-software** [comment]
Great, the mouse cursor works. I could solve the problem in the app by clearing the app cache.
Just one more thing: For grid I have separate entities configured for consumption and production. When clicking the grid circle, it always open the details view of the production entity. I dont know if and how it would be possible to differentiate both?

Did you get any response from @ulic75 ? Can the PR be merged so we can update via HACS? Or should we rather switch to your fork for any further improvements?

**Comment by ulic75** [comment]
I have tried to post elsewhere, but currently I don't plan to offer additional features with this card.  I hope to be able to maintain feature parity with the official Energy Distribution card, and to maintain any existing features that are above on beyond.  But I simply lack the time (and currently the desire) necessary to ensure additional features such as this PR are functional and maintained.  I know this may disappoint many, but it's just the where things are are right now.

That said I have no problem if someone wants to fork the project and create their own card based on my work (which is mostly based on the work of the HA team :))

**Comment by Patrick762** [comment]
I alredy started with a similar card (without the water circle) with the components splitted (easier to maintain than one file). I'll link it here once it's stable if it's ok for you @ulic75

**Comment by ulic75** [comment]
@Patrick762 I don't mind you sharing a link to your fork if that is what you're talking about.  I'd prefer not just linking zip files as this isn't the appropriate place to carry on conversations about you changes.  I didn't say so early, but I do appreciate your wanting to chip in.

**Comment by matthewbyrne** [comment]
Any beta version of this, rather than manual zip installs?

**Comment by Patrick762** [comment]
I'll create a new fork with the changes. All changes from now on are only in the fork. I'll also close this PR

**Pull request closed without merging**
